version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./.docker/apache-php-composer.Dockerfile
    image: devenv/laravel
    container_name: devenv_backend
    ports:
      - 8087:8007
    volumes:
      - ./backend:/backend
  frontend:
    build:
      context: ./frontend
      dockerfile: ./.docker/node-angularcli.Dockerfile
    image: devenv/angular
    container_name: devenv_frontend
    command: tail -f /dev/null
    ports:
      - 4202:4202
      - 9877:9877
    volumes:
      - ./frontend:/frontend
