version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./.docker/apache-php-composer.Dockerfile
    image: devenv/laravel
    container_name: devenv_backend
    ports:
      - 8087:8007
    volumes:
      - ./backend:/backend
    environment:
      DB_HOST: '127.0.0.1'
      DB_DATABASE: app_db
      DB_USERNAME: root
      DB_PASSWORD: '123'
  frontend:
    build:
      context: ./frontend
      dockerfile: ./.docker/node-angularcli.Dockerfile
    image: devenv/angular
    container_name: devenv_frontend
    command: tail -f /dev/null
    ports:
      - 4202:4202
      - 9877:9877
    volumes:
      - ./frontend:/frontend
  mysql:
    image: mysql:latest
    container_name: devenv_mysql
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: '123'
